# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Clones the repository on the local machine
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install npm
      run: npm install
    - name: Start the app
      run: npm run start &
    - name: Run tests
      run: npm run test

  security_test:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name: Clones the repository on the local machine
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install npm
      run: npm install
    - name: Start the app
      run: npm run start &
    - name: Run tests
      run: npm audit
